In [1]:
import numpy as np
import math
import pandas as pd

In [2]:
a=np.array([10,9,8,5])
b=np.array([2,9,5,6])


In [3]:
c= a-b


In [4]:
print(c)

[ 8  0  3 -1]


In [5]:
d=a*b

In [6]:
print(d)

[20 81 40 30]


In [9]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,8],[5,4]])

In [10]:
print(A*B)

[[2 8]
 [0 4]]


In [11]:
print(A@B)

[[ 7 12]
 [ 5  4]]


In [12]:
A.shape

(2, 2)

In [13]:
print(A.dtype)

int32


In [14]:
C=A+B

In [15]:
print(C)

[[3 9]
 [5 5]]


In [16]:
print(C.dtype)

int32


In [17]:
print(C.sum())
print(C.max())
print(C.min())
print(C.mean())

22
9
3
5.5


In [19]:
c=np.arange(1,16,1).reshape(3,5)

In [20]:
print(C)

[[3 9]
 [5 5]]


In [21]:
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [1]:
c=np.arange(0,36,1).reshape(6,6)

NameError: name 'np' is not defined