In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
import math

In [6]:
a=np.array([1,2,3,4])


In [7]:
a

array([1, 2, 3, 4])

In [8]:
a[1]

2

In [9]:
b=np.array([[1,2],[3,4],[5,6]])

In [10]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
b[2,1]

6

In [12]:
np.array([b[0,0],b[2,1],b[1,1]])

array([1, 6, 4])

# boolean

In [13]:
print(b>5)

[[False False]
 [False False]
 [False  True]]


In [14]:
print(b[b>5])

[6]
