In [1]:
import numpy as np
import math 
import pandas as pd


In [2]:
a=np.array([1,2,3])

In [3]:
a


array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
b= np.array([[1,1,2],[2,3,5]])

In [6]:
b

array([[1, 1, 2],
       [2, 3, 5]])

In [7]:
b.shape

(2, 3)

In [8]:
b.dtype

dtype('int32')

In [9]:
c=np.array([2.2,1.2,5])

In [10]:
c

array([2.2, 1.2, 5. ])

In [11]:
d= np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
e=np.ones((2,3))

In [13]:
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.rand(2,3)

array([[0.18799524, 0.63401776, 0.56724891],
       [0.34087093, 0.03055676, 0.64661906]])

In [15]:
f=np.arange(10,50,2)

In [16]:
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [17]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])