In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import math

In [4]:
a=np.array([2,3,4,5,6,7])

In [5]:
print(a[:3])

[2 3 4]


In [8]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b[:2,1:3]

array([[2, 3],
       [5, 6]])